### ISSUE TITLE
Just-Install should support 64 bit only apps

### ISSUE THREAD

**Issue by eveldee0680** [just-install/registry#94] opened 2018-07-06 13:38 UTC
When you only add the "x86_64" entry for a package, the json-schema throw an error and the test fail.

So we can't add software like GitHub-Desktop which are 64bit only, except if we use "x86" for this, but 32 bit users will see the package.

**Comment by geek1011** [comment] 2018-07-06 15:19
Yep. This is currently a limitation of just-install, but a fix is planned.

Duplicate of just-install/just-install#235.

**Closed by geek1011** 2018-07-06 15:19 UTC
